// <auto-generated />
using System;
using CompetitionDataLayer;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CompetitionDataLayer.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240718082845_InitialCreatetests")]
    partial class InitialCreatetests
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CompetitionDomainModel.Competition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Competitions");

                    b.HasData(
                        new
                        {
                            Id = new Guid("ea9c3f9b-957a-4ec3-bb40-3327c5a08f1b"),
                            Name = "Simmning"
                        },
                        new
                        {
                            Id = new Guid("91077f23-927e-43b2-9bac-7af409a06282"),
                            Name = "Tennis"
                        },
                        new
                        {
                            Id = new Guid("97beff8c-3a08-4c88-85d3-70de1853297a"),
                            Name = "Dans"
                        },
                        new
                        {
                            Id = new Guid("668b7ad2-977c-4025-a738-e3cd2232dfcf"),
                            Name = "fotboll"
                        },
                        new
                        {
                            Id = new Guid("b794e9a2-3fa8-4041-a948-034189216bbd"),
                            Name = "E-sport"
                        });
                });

            modelBuilder.Entity("CompetitionDomainModel.Participant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CompetitionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CompetitionId");

                    b.ToTable("Participants");

                    b.HasData(
                        new
                        {
                            Id = new Guid("02c6926b-3445-4a27-92fd-7c1e62168c38"),
                            CompetitionId = new Guid("b794e9a2-3fa8-4041-a948-034189216bbd"),
                            Name = "Saga"
                        },
                        new
                        {
                            Id = new Guid("545ba864-36a8-40f9-9445-52df6fddcbd7"),
                            CompetitionId = new Guid("b794e9a2-3fa8-4041-a948-034189216bbd"),
                            Name = "Ulv"
                        },
                        new
                        {
                            Id = new Guid("52b5988d-e1fa-4010-af9d-631a3584c9bc"),
                            CompetitionId = new Guid("b794e9a2-3fa8-4041-a948-034189216bbd"),
                            Name = "Embla"
                        },
                        new
                        {
                            Id = new Guid("803d7cc5-a497-4d56-910a-0a4943a6cfee"),
                            CompetitionId = new Guid("91077f23-927e-43b2-9bac-7af409a06282"),
                            Name = "Torgny"
                        },
                        new
                        {
                            Id = new Guid("51d87b0c-573d-4664-a385-937436fced10"),
                            CompetitionId = new Guid("97beff8c-3a08-4c88-85d3-70de1853297a"),
                            Name = "Gisle"
                        },
                        new
                        {
                            Id = new Guid("83ff27a9-916a-4001-8bd9-ec12ba46dc9b"),
                            CompetitionId = new Guid("97beff8c-3a08-4c88-85d3-70de1853297a"),
                            Name = "Erak"
                        },
                        new
                        {
                            Id = new Guid("2eaf5367-04cf-4222-bb6e-794c8ed5c2c9"),
                            CompetitionId = new Guid("97beff8c-3a08-4c88-85d3-70de1853297a"),
                            Name = "Haldur"
                        },
                        new
                        {
                            Id = new Guid("e57e164c-3e23-4740-a0a0-4eeb0367c02f"),
                            CompetitionId = new Guid("ea9c3f9b-957a-4ec3-bb40-3327c5a08f1b"),
                            Name = "Saxe"
                        },
                        new
                        {
                            Id = new Guid("e6199131-33d1-413c-aa3f-30637c8cd0cb"),
                            CompetitionId = new Guid("668b7ad2-977c-4025-a738-e3cd2232dfcf"),
                            Name = "Estrid"
                        },
                        new
                        {
                            Id = new Guid("161ea10f-c77b-45b9-b4d5-7d5808fb27de"),
                            CompetitionId = new Guid("668b7ad2-977c-4025-a738-e3cd2232dfcf"),
                            Name = "Erling"
                        });
                });

            modelBuilder.Entity("CompetitionDomainModel.Participant", b =>
                {
                    b.HasOne("CompetitionDomainModel.Competition", "Competition")
                        .WithMany("Participants")
                        .HasForeignKey("CompetitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Competition");
                });

            modelBuilder.Entity("CompetitionDomainModel.Competition", b =>
                {
                    b.Navigation("Participants");
                });
#pragma warning restore 612, 618
        }
    }
}
