// <auto-generated />
using System;
using CompetitionDataLayer;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CompetitionDataLayer.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240718070444_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CompetitionDomainModel.Competition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Competitions");

                    b.HasData(
                        new
                        {
                            Id = new Guid("d111e3bf-6ec5-4b16-acef-175b4b64d9bc"),
                            Name = "Simmning"
                        },
                        new
                        {
                            Id = new Guid("453294c3-3497-4d60-af9a-fcd176bde7ee"),
                            Name = "Tennis"
                        },
                        new
                        {
                            Id = new Guid("dcace436-7464-4db0-b217-0aa9178b28c3"),
                            Name = "Dans"
                        },
                        new
                        {
                            Id = new Guid("a56bdd04-adfd-4c24-9750-1ebeacbd3ab7"),
                            Name = "fotboll"
                        },
                        new
                        {
                            Id = new Guid("e2c4e149-e541-4f3b-8d17-4f66277ea0a4"),
                            Name = "E-sport"
                        });
                });

            modelBuilder.Entity("CompetitionDomainModel.Participant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CompetitionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CompetitionId");

                    b.ToTable("Participants");

                    b.HasData(
                        new
                        {
                            Id = new Guid("f399a73f-c5d9-4cb0-83a3-e0e9d9e8ce6d"),
                            CompetitionId = new Guid("e2c4e149-e541-4f3b-8d17-4f66277ea0a4"),
                            Name = "Saga"
                        },
                        new
                        {
                            Id = new Guid("6945876f-a8f5-4fab-9a67-b460e6a0bbe0"),
                            CompetitionId = new Guid("e2c4e149-e541-4f3b-8d17-4f66277ea0a4"),
                            Name = "Ulv"
                        },
                        new
                        {
                            Id = new Guid("50239484-3d3c-4c33-a3f3-b5cd1170e8c3"),
                            CompetitionId = new Guid("e2c4e149-e541-4f3b-8d17-4f66277ea0a4"),
                            Name = "Embla"
                        },
                        new
                        {
                            Id = new Guid("a9e7045e-d9e5-452a-8d7d-2e51f5b55137"),
                            CompetitionId = new Guid("453294c3-3497-4d60-af9a-fcd176bde7ee"),
                            Name = "Torgny"
                        },
                        new
                        {
                            Id = new Guid("1ab6c293-ea80-404b-997d-bfd63c4c064c"),
                            CompetitionId = new Guid("dcace436-7464-4db0-b217-0aa9178b28c3"),
                            Name = "Gisle"
                        },
                        new
                        {
                            Id = new Guid("df40ce10-6c3f-4b58-b3e5-fdd6b20cde88"),
                            CompetitionId = new Guid("dcace436-7464-4db0-b217-0aa9178b28c3"),
                            Name = "Erak"
                        },
                        new
                        {
                            Id = new Guid("4c5f5fe8-26cd-4ee3-923c-9ecb54744c5c"),
                            CompetitionId = new Guid("dcace436-7464-4db0-b217-0aa9178b28c3"),
                            Name = "Haldur"
                        },
                        new
                        {
                            Id = new Guid("144ef59b-82d7-4db2-988e-d7cbe4adf8bb"),
                            CompetitionId = new Guid("d111e3bf-6ec5-4b16-acef-175b4b64d9bc"),
                            Name = "Saxe"
                        },
                        new
                        {
                            Id = new Guid("4493a978-3df2-4f74-bf34-68d1fd941a8d"),
                            CompetitionId = new Guid("a56bdd04-adfd-4c24-9750-1ebeacbd3ab7"),
                            Name = "Estrid"
                        },
                        new
                        {
                            Id = new Guid("71b818d9-1090-44c3-b211-9f12daed903b"),
                            CompetitionId = new Guid("a56bdd04-adfd-4c24-9750-1ebeacbd3ab7"),
                            Name = "Erling"
                        });
                });

            modelBuilder.Entity("CompetitionDomainModel.Participant", b =>
                {
                    b.HasOne("CompetitionDomainModel.Competition", "Competition")
                        .WithMany("Participants")
                        .HasForeignKey("CompetitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Competition");
                });

            modelBuilder.Entity("CompetitionDomainModel.Competition", b =>
                {
                    b.Navigation("Participants");
                });
#pragma warning restore 612, 618
        }
    }
}
